/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    BasicLayout: typeof import('./src/layouts/BasicLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LabelSelection: typeof import('./src/components/LabelSelection/index.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagList: typeof import('./src/components/TagList/index.vue')['default']
    Team: typeof import('./src/pages/team.vue')['default']
    UserList: typeof import('./src/components/UserList/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
  }
}
